#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Jan 19 00:03:26 CET 2026
maven-metadata-MaryTTS.xml.error=
maven-metadata-MaryTTS.xml.lastUpdated=1768777406318
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1768773047283
