#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Jan 19 00:15:07 CET 2026
maven-metadata-MaryTTS.xml.error=
maven-metadata-central.xml.lastUpdated=1768773047157
maven-metadata-MaryTTS.xml.lastUpdated=1768778107157
maven-metadata-central.xml.error=
