#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Sun Jan 18 16:24:28 CET 2026
maven-metadata-MaryTTS.xml.error=
maven-metadata-MaryTTS.xml.lastUpdated=1768749868179
