#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Jan 19 00:15:06 CET 2026
maven-metadata-MaryTTS.xml.error=
maven-metadata-central.xml.lastUpdated=1768773047021
maven-metadata-MaryTTS.xml.lastUpdated=1768778106751
maven-metadata-central.xml.error=
